name: cancelable_http_client
version: 1.0.0
description: A cancelable HTTP client is a wrapper over `http.Client` that allows to cancel a request or the operation of receiving data from the response or the operation of sending data via request.
homepage: https://github.com/mezoni/cancelable_http_client
topics:
 - cancellation
 - http
 - http-client
 - network
 - streams
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  http: ^1.6.0
  multitasking: ^4.6.0
dev_dependencies:
  defer: ^1.0.0
  lints: ^6.1.0
  mime: ^2.0.0
  test: ^1.31.0
